# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/market.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/market.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/market.proto\x12\x06market\"O\n\x0bTickRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x0e\n\x06volume\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"0\n\x0cTickResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x88\x01\n\x11MarketDataService\x12\x37\n\nSubmitTick\x12\x13.market.TickRequest\x1a\x14.market.TickResponse\x12:\n\x0bStreamTicks\x12\x13.market.TickRequest\x1a\x14.market.TickResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.market_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TICKREQUEST']._serialized_start=31
  _globals['_TICKREQUEST']._serialized_end=110
  _globals['_TICKRESPONSE']._serialized_start=112
  _globals['_TICKRESPONSE']._serialized_end=160
  _globals['_MARKETDATASERVICE']._serialized_start=163
  _globals['_MARKETDATASERVICE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
